namespace QwenLocalChat.Core;

public static class HanhuaCommand
{
    public const string MitRootEnv = "HANHUA_MIT_ROOT";
    public const string LocalModelEnv = "HANHUA_LOCAL_MODEL";

    public static string? ResolveFillModel(LocalChatSettings settings, string? localModel = null)
    {
        if (!string.IsNullOrWhiteSpace(localModel))
            return localModel.Trim();
        return string.IsNullOrWhiteSpace(settings.HanhuaFillProfileId) ? null : settings.HanhuaFillProfileId.Trim();
    }

    public static string? Validate(LocalChatSettings settings, HanhuaKind kind)
    {
        if (string.IsNullOrWhiteSpace(settings.HanhuaPackRoot) || string.IsNullOrWhiteSpace(settings.HanhuaPythonExe))
            return "请先在设置里填写汉化工具包和 Python 路径。";
        if (!File.Exists(settings.HanhuaPythonExe))
            return "设置里的 Python 可执行文件不存在。";
        if (!Directory.Exists(settings.HanhuaPackRoot))
            return "设置里的汉化工具包目录不存在。";
        var tools = Path.Combine(settings.HanhuaPackRoot, "tools");
        if (!File.Exists(Path.Combine(tools, "one_click_rm.py")))
            return "汉化工具包缺少 tools/one_click_rm.py。";
        if (!File.Exists(Path.Combine(tools, "one_click_unity.py")))
            return "汉化工具包缺少 tools/one_click_unity.py。";
        if (kind == HanhuaKind.Image)
        {
            if (string.IsNullOrWhiteSpace(settings.HanhuaMitRoot))
                return "图片汉化需要在设置里填写 manga-image-translator 目录。";
            if (!Directory.Exists(settings.HanhuaMitRoot))
                return "设置里的 manga-image-translator 目录不存在。";
            if (!File.Exists(Path.Combine(tools, "ocr_extract_local.py"))
                || !File.Exists(Path.Combine(tools, "fill_ocr_local.py"))
                || !File.Exists(Path.Combine(tools, "typeset_ocr_local.py")))
                return "汉化工具包缺少图片脚本。";
        }
        return null;
    }

    public static string ImageWorkPath(string packRoot, string jobId)
        => Path.Combine(packRoot, "work", "_local_ai", jobId);

    public static bool LooksLikeUnity(string path)
        => ResolveUnityRoot(path) is not null;

    public static string? ResolveUnityRoot(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return null;
        var root = Path.GetFullPath(path);
        if (!Directory.Exists(root))
            return null;
        if (IsUnityRoot(root))
            return root;
        try
        {
            var hits = Directory.EnumerateDirectories(root)
                .Where(IsUnityRoot)
                .Take(2)
                .ToList();
            return hits.Count == 1 ? hits[0] : null;
        }
        catch (IOException)
        {
            return null;
        }
        catch (UnauthorizedAccessException)
        {
            return null;
        }
    }

    public static bool UnityHasDump(string path)
    {
        var root = ResolveUnityRoot(path);
        if (root is null)
            return false;
        var dump = Path.Combine(root, "BepInEx", "Translation", "zh-CN", "Text", "_AutoGeneratedTranslations.txt");
        return File.Exists(dump) && new FileInfo(dump).Length > 0;
    }

    public static HanhuaLaunch Game(
        LocalChatSettings settings,
        HanhuaEngine engine,
        string gamePath,
        string? localModel = null)
    {
        if (LooksLikeUnity(gamePath))
            return Unity(settings, engine, gamePath, fill: engine == HanhuaEngine.LocalQwen, localModel);
        var launch = Python(
            settings,
            "one_click_rm.py",
            engine == HanhuaEngine.LocalQwen
                ? ["--local", "--progress-jsonl", gamePath]
                : ["--progress-jsonl", gamePath]);
        if (engine != HanhuaEngine.LocalQwen)
            return launch;
        return WithFillModel(launch, settings, localModel);
    }

    public static HanhuaLaunch Unity(
        LocalChatSettings settings,
        HanhuaEngine engine,
        string gamePath,
        bool fill,
        string? localModel = null)
    {
        var root = ResolveUnityRoot(gamePath) ?? Path.GetFullPath(gamePath);
        var args = new List<string> { "--progress-jsonl" };
        if (fill)
            args.Add("--fill");
        args.Add(root);
        var launch = Python(settings, "one_click_unity.py", args);
        if (!fill || engine != HanhuaEngine.LocalQwen)
            return launch;
        return WithFillModel(launch, settings, localModel);
    }

    public static HanhuaLaunch ImageOcr(LocalChatSettings settings, string sourcePath, string workPath)
        => Python(settings, "ocr_extract_local.py", ["--progress-jsonl", sourcePath, workPath], includeMit: true);

    public static HanhuaLaunch ImageOcrCatchUp(LocalChatSettings settings, string sourcePath, string workPath)
        => Python(settings, "ocr_extract_local.py", ["--progress-jsonl", "--missing-only", sourcePath, workPath], includeMit: true);

    public static HanhuaLaunch ImageFill(
        LocalChatSettings settings,
        HanhuaEngine engine,
        string workPath,
        string? localModel = null)
    {
        var launch = Python(
            settings,
            "fill_ocr_local.py",
            engine == HanhuaEngine.Aliyun
                ? ["--mt", "--progress-jsonl", workPath]
                : ["--progress-jsonl", workPath]);
        if (engine == HanhuaEngine.Aliyun)
            return launch;
        return WithFillModel(launch, settings, localModel);
    }

    public static HanhuaLaunch ImageTypeset(LocalChatSettings settings, string workPath)
        => Python(settings, "typeset_ocr_local.py", ["--progress-jsonl", workPath], includeMit: true);

    public static HanhuaLaunch ImageTypesetCatchUp(LocalChatSettings settings, string workPath)
        => Python(settings, "typeset_ocr_local.py", ["--progress-jsonl", "--changed-only", workPath], includeMit: true);

    public static HanhuaGpuNeed GpuNeed(HanhuaKind kind, HanhuaEngine engine, HanhuaPhase phase)
    {
        if (kind == HanhuaKind.Game)
        {
            if (phase is HanhuaPhase.Copy or HanhuaPhase.Extract)
                return HanhuaGpuNeed.None;
            return engine == HanhuaEngine.LocalQwen ? HanhuaGpuNeed.GalTransl : HanhuaGpuNeed.None;
        }
        return phase switch
        {
            HanhuaPhase.Ocr or HanhuaPhase.Typeset => HanhuaGpuNeed.Mit,
            HanhuaPhase.Fill => engine == HanhuaEngine.LocalQwen ? HanhuaGpuNeed.GalTransl : HanhuaGpuNeed.None,
            _ => HanhuaGpuNeed.None,
        };
    }

    public static IReadOnlyList<HanhuaPhase> Phases(HanhuaKind kind)
        => kind == HanhuaKind.Game
            ? [HanhuaPhase.Copy, HanhuaPhase.Extract, HanhuaPhase.Translate, HanhuaPhase.Inject]
            : [HanhuaPhase.Ocr, HanhuaPhase.Fill, HanhuaPhase.Typeset];

    public static IReadOnlyList<HanhuaPhase> UnityPhases { get; } = [HanhuaPhase.Copy, HanhuaPhase.Translate];

    private static bool IsUnityRoot(string root)
    {
        if (File.Exists(Path.Combine(root, "UnityPlayer.dll"))
            || File.Exists(Path.Combine(root, "GameAssembly.dll")))
            return true;
        try
        {
            return Directory.EnumerateDirectories(root, "*_Data").Any();
        }
        catch (IOException)
        {
            return false;
        }
        catch (UnauthorizedAccessException)
        {
            return false;
        }
    }

    private static HanhuaLaunch WithFillModel(HanhuaLaunch launch, LocalChatSettings settings, string? localModel)
    {
        var model = ResolveFillModel(settings, localModel);
        if (model is null)
            return launch;
        var env = new Dictionary<string, string>(launch.Environment, StringComparer.Ordinal)
        {
            [LocalModelEnv] = model,
        };
        return launch with { Environment = env };
    }

    private static HanhuaLaunch Python(
        LocalChatSettings settings,
        string scriptName,
        IReadOnlyList<string> scriptArgs,
        bool includeMit = false)
    {
        var pack = Path.GetFullPath(settings.HanhuaPackRoot);
        var args = new List<string> { "-u", Path.Combine(pack, "tools", scriptName) };
        args.AddRange(scriptArgs);
        var env = new Dictionary<string, string>(StringComparer.Ordinal)
        {
            ["PYTHONUTF8"] = "1",
            ["PYTHONIOENCODING"] = "utf-8",
        };
        if (includeMit && !string.IsNullOrWhiteSpace(settings.HanhuaMitRoot))
            env[MitRootEnv] = Path.GetFullPath(settings.HanhuaMitRoot);
        return new HanhuaLaunch(
            Path.GetFullPath(settings.HanhuaPythonExe),
            args,
            pack,
            env);
    }
}
